version: "2"

services:
  web:
    build: .
    image: ovhchatbot
    ports:
      - "80:80"
    depends_on:
      - mongo
    environment:
      - MONGO=mongodb://mongo:27017/ovhchatbot
    env_file:
      - .env

  mongo:
    image: mongo
    ports:
      - "27017:27017"
